version: '3.9'

services:
  monitor-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regulatory-monitor
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
